version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always