version: '3.1'

services:
  server:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always