import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import WebNavbar from "@/components/WebNavbar";

// const inter = Poppins({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Goat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WebNavbar />
        {children}
      </body>
    </html>
  );
}
