import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Providers } from "./providers";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Crypto Goat App",
  description: "Generated by create next app",
};

const WebNavbar = dynamic(() => import("../components/WebNavbar"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <WebNavbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
